name = "cl1p-cleanup"
main = "scheduled.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "cl1p-db"
database_id = "13fbb1e9-bb76-4345-9a21-235dfb0fa6c3"

[[r2_buckets]]
binding = "FILES"
bucket_name = "cl1p-files"

[triggers]
crons = ["0 * * * *"]
